name: Generating debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        path: .

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build APK with Gradle
        run: ./gradlew bootJar
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: livechat
          path: build/libs/*.jar